substitutions:
  name: heatpump
  friendlyName: Ecodan Heatpump

esphome:
  name: ${name}
  friendly_name: ${friendlyName}

esp8266:
  board: esp01_1m
  framework:
    platform_version: 4.2.1

packages:
  ecodan-heatpump: github://tobias-93/esphome-ecodan-heatpump/heatpump.yaml@main